language: bash

sudo: required

branches:
  only:
    - master

services:
  - docker

script:
 - docker build --tag orleika/nginx .
 - docker run -d -p 80:80 orleika/nginx
 - sleep 5
- curl -sSf localhost
